[package]
name = "sqlmodel-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "SQLite driver for SQLModel Rust"
homepage.workspace = true
documentation = "https://docs.rs/sqlmodel-sqlite"
readme = "README.md"
keywords = ["sqlite", "sql", "database", "driver", "sqlmodel"]
categories = ["database", "database-implementations"]

[lints]
workspace = true

[features]
default = []
console = ["dep:sqlmodel-console"]

[dependencies]
sqlmodel-core.workspace = true
asupersync.workspace = true
serde.workspace = true
serde_json.workspace = true

# Optional console support
sqlmodel-console = { workspace = true, optional = true }

[build-dependencies]

[dev-dependencies]
